In [1]:
import pandas as pd
from collections import defaultdict
from tqdm import tqdm
import os
import numpy as np

### interaction のデータを読み込み

In [2]:
interaction_file_path = './master_table/all_interaction_data.csv'

In [3]:
df = pd.read_csv(interaction_file_path)
df.head(10)

,Unnamed: 0,user_id,item_id,org_id,freebase_id,track_name,artist_id,artist_name
0,0,0,72,16782,m.0qh8tx,Needles and Pins,362.0,Deftones
1,1,0,73,16781,m.0qh8v3,Minerva,362.0,Deftones
2,2,0,74,16780,m.0qh8vb,Good Morning Beautiful,362.0,Deftones
3,3,0,75,16779,m.0qh8vk,Deathblow,362.0,Deftones
4,4,0,76,16778,m.0w2yfq,When Girls Telephone Boys,362.0,Deftones
5,5,0,77,16777,m.0qh8v_,Battle-Axe,362.0,Deftones
6,6,0,9725,16776,m.0qh8w6,Lucky You,362.0,Deftones
7,7,0,9726,16775,m.0dvhv4c,Bloody Cape,362.0,Deftones
8,8,0,9727,16774,m.0qh8wn,Anniversary of an Uninteresting Event,362.0,Deftones
9,9,0,9762,16773,m.0qh8ww,Moana,362.0,Deftones

In [4]:
artists = list(df['artist_name'].unique())

In [5]:
artist_list = list(df['artist_name'])
artist_np = np.array(artist_list)

interaction_count = []

for artist in tqdm(artists):
    count = np.count_nonzero(artist_np == artist)
    interaction_count.append(count)

 44%|██████████████████████████████████▏                                           | 1481/3383 [00:24<00:32, 58.82it/s]C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  import sys
100%|██████████████████████████████████████████████████████████████████████████████| 3383/3383 [00:56<00:00, 57.77it/s]

In [8]:
artists_population_df = pd.DataFrame(
    data = {
        'artist_name' : artists,
        'interaction' : interaction_count
    },
    columns = ['artist_name', 'interaction']
)

In [9]:
artists_population_df.head(10)

      artist_name  interaction
0        Deftones         2511
1  Marilyn Manson         2390
2      Rob Zombie          805
3    Apocalyptica          882
4     Soundgarden          799
5       The Doors          325
6     Tim Buckley          101
7     Wolf Parade          111
8       Buzzcocks           98
9      Black Lips          137

In [10]:
artists_population_df = artists_population_df.sort_values('interaction', ascending=False)
artists_population_df = artists_population_df.reset_index(drop=True)
artists_population_df.head(10)

               artist_name  interaction
0           Arctic Monkeys         4754
1              Linkin Park         4357
2              The Beatles         4271
3                    Queen         4241
4                Daft Punk         3727
5                     Muse         3712
6                      Sia         3587
7        The White Stripes         3520
8  Queens of the Stone Age         3327
9    Red Hot Chili Peppers         3066

In [11]:
artists_population_df.to_csv('artists_population.csv', encoding='utf_8_sig')

### 特定のアーティストの順位を検索

In [6]:
artists_population_df = pd.read_csv('artists_population.csv')

In [8]:
artist = 'The Chemical Brothers'
artists_population_df[artists_population_df['artist_name'] == artist]

     Unnamed: 0            artist_name  interaction
178         178  The Chemical Brothers          792

### 人気のアーティストを抽出

In [12]:
top_artists_df = artists_population_df[:250]

In [13]:
top_artists_df.tail(5)

              artist_name  interaction
245  The Sisters of Mercy          636
246       Cradle of Filth          636
247     Cage the Elephant          634
248             DJ Shadow          631
249                Weezer          627

In [14]:
top_artist_list = top_artists_df['artist_name']
top_artist_intaraction_df = df[df['artist_name'].isin(top_artist_list)]

In [15]:
top_artist_intaraction_df.columns

Index(['Unnamed: 0', 'user_id', 'item_id', 'org_id', 'freebase_id',
       'track_name', 'artist_id', 'artist_name'],
      dtype='object')

In [16]:
top_artist_intaraction_df = top_artist_intaraction_df.drop("Unnamed: 0", axis=1)
top_artist_intaraction_df.head()

,user_id,item_id,org_id,freebase_id,track_name,artist_id,artist_name
0,0,72,16782,m.0qh8tx,Needles and Pins,362.0,Deftones
1,0,73,16781,m.0qh8v3,Minerva,362.0,Deftones
2,0,74,16780,m.0qh8vb,Good Morning Beautiful,362.0,Deftones
3,0,75,16779,m.0qh8vk,Deathblow,362.0,Deftones
4,0,76,16778,m.0w2yfq,When Girls Telephone Boys,362.0,Deftones

### 人気のアーティストのトラックの出現回数をカウント

In [17]:
items = list(top_artist_intaraction_df['item_id'].unique())
item_list = list(top_artist_intaraction_df['item_id'])

In [55]:
items_np = np.array(item_list)

interaction_count = []

for item in tqdm(items):
    count = np.count_nonzero(items_np == item)
    interaction_count.append(count)

100%|██████████████████████████████████████████████████████████████████████████| 12672/12672 [00:02<00:00, 4356.01it/s]

In [105]:
item_interaction_df = pd.DataFrame(
    data = {
        'item_id' : items,
        'interaction' : interaction_count
    },
    columns=['item_id', 'interaction']
)

In [106]:
item_interaction_df['item_id'] = item_interaction_df['item_id']
item_interaction_df.head(5)
item_interaction_df.to_csv('item_interaction.csv')

In [100]:
len(item_interaction_df)

12672

In [107]:
item_meta_data_df = df.loc[:, ['item_id', 'track_name', 'artist_name']]
item_meta_data_df['item_id'] = item_meta_data_df['item_id']
item_meta_data_df.to_csv('item_meta_data.csv')
item_meta_data_df.head()

   item_id                 track_name artist_name
0       72           Needles and Pins    Deftones
1       73                    Minerva    Deftones
2       74     Good Morning Beautiful    Deftones
3       75                  Deathblow    Deftones
4       76  When Girls Telephone Boys    Deftones

### 各アイテムの出現回数とメタ情報を含んだDataFrameを作成

In [155]:
item_interaction_df = pd.read_csv('item_interaction.csv')
item_interaction_df.head()

   Unnamed: 0  item_id  interaction
0           0       72           42
1           1       73           99
2           2       74           42
3           3       75           31
4           4       76           37

In [156]:
df_1 = item_interaction_df.drop('Unnamed: 0', axis=1)
df_1.head()

   item_id  interaction
0       72           42
1       73           99
2       74           42
3       75           31
4       76           37

In [158]:
item_meta_data_df = pd.read_csv('item_meta_data.csv')
df_2 = item_meta_data_df.drop('Unnamed: 0', axis=1)
df_2.head(100)

    item_id                              track_name     artist_name
0        72                        Needles and Pins        Deftones
1        73                                 Minerva        Deftones
2        74                  Good Morning Beautiful        Deftones
3        75                               Deathblow        Deftones
4        76               When Girls Telephone Boys        Deftones
5        77                              Battle-Axe        Deftones
6      9725                               Lucky You        Deftones
7      9726                             Bloody Cape        Deftones
8      9727   Anniversary of an Uninteresting Event        Deftones
9      9762                                   Moana        Deftones
10      105                             Swerve City        Deftones
11    24967                               Godeatgod  Marilyn Manson
12     8133                          The Fight Song  Marilyn Manson
13    14852                        Disposable Teens  Marilyn Manson
14     8178                          President Dead  Marilyn Manson
15    24082                  Cruci-fiction in Space  Marilyn Manson
16     7933                     A Place in the Dirt  Marilyn Manson
17     8201                             Lamb of God  Marilyn Manson
18    24345                              Born Again  Marilyn Manson
19     7946                            Burning Flag  Marilyn Manson
20    32430                        The Fall of Adam  Marilyn Manson
21     8167               Mechanical Animals (live)  Marilyn Manson
22        1                 Teenage Nosferatu Pussy      Rob Zombie
23     8250                   Revelation Revolution      Rob Zombie
24     9728                Theme for the Rat Vendor      Rob Zombie
25     9729  Ging Gang Gong De Do Gong De Laga Raga      Rob Zombie
26     7939         Rock and Roll (in a Black Hole)      Rob Zombie
27     9730    Behold, The Pretty Filthy Creatures!      Rob Zombie
28     9731                      White Trash Freaks      Rob Zombie
29     9733                          Lucifer Rising      Rob Zombie
..      ...                                     ...             ...
70     3558                   Mary of the Wild Moor     Johnny Cash
71    39068                                Deadlock             Can
72     8949                               Bathwater        No Doubt
73      297               Dusk (Dark Is Descending)        Anathema
74      298                   The Lost Song, Part 3        Anathema
75      299                                Anathema        Anathema
76      300                        You're Not Alone        Anathema
77      301                               Firelight        Anathema
78      302                      Distant Satellites        Anathema
79      303                            Take Shelter        Anathema
80     3128                                  Advent           Opeth
81     3311          The Night and the Silent Water           Opeth
82     7218                                  Nectar           Opeth
83     7219                     Black Rose Immortal           Opeth
84     8115                     To Bid You Farewell           Opeth
85      289                In Mist She Was Standing           Opeth
86      290                  Under the Weeping Moon           Opeth
87      291                 The Twilight Is My Robe           Opeth
88      292                  The Apostle in Triumph           Opeth
89     3330                              Windowpane           Opeth
90     2692                      In My Time of Need           Opeth
91     3325               Death Whispered a Lullaby           Opeth
92     3323                                 Closure           Opeth
93     2967                      To Rid the Disease           Opeth
94     3332                          Ending Credits           Opeth
95     3327                                Weakness           Opeth
96     3330                              Windowpane           Opeth
97     2692                      In My Time of Need           Opeth
98     3325               Death Whispered a Lullaby           Opeth
99     3323                                 Closure           Opeth

[100 rows x 3 columns]

In [159]:
item_df = pd.merge(
    right=df_1,
    left=df_2, 
    on='item_id',
    how='left'
)
item_df.head(100)

,item_id,track_name,artist_name,interaction
0,72,Needles and Pins,Deftones,42.0
1,73,Minerva,Deftones,99.0
2,74,Good Morning Beautiful,Deftones,42.0
3,75,Deathblow,Deftones,31.0
4,76,When Girls Telephone Boys,Deftones,37.0
5,77,Battle-Axe,Deftones,41.0
6,9725,Lucky You,Deftones,51.0
7,9726,Bloody Cape,Deftones,45.0
8,9727,Anniversary of an Uninteresting Event,Deftones,29.0
9,9762,Moana,Deftones,26.0
10,105,Swerve City,Deftones,131.0
11,24967,Godeatgod,Marilyn Manson,16.0
12,8133,The Fight Song,Marilyn Manson,88.0
13,14852,Disposable Teens,Marilyn Manson,68.0
14,8178,President Dead,Marilyn Manson,13.0
15,24082,Cruci-fiction in Space,Marilyn Manson,20.0
16,7933,A Place in the Dirt,Marilyn Manson,18.0
17,8201,Lamb of God,Marilyn Manson,25.0
18,24345,Born Again,Marilyn Manson,18.0
19,7946,Burning Flag,Marilyn Manson,17.0
20,32430,The Fall of Adam,Marilyn Manson,15.0
21,8167,Mechanical Animals (live),Marilyn Manson,4.0
22,1,Teenage Nosferatu Pussy,Rob Zombie,25.0
23,8250,Revelation Revolution,Rob Zombie,20.0
24,9728,Theme for the Rat Vendor,Rob Zombie,16.0
25,9729,Ging Gang Gong De Do Gong De Laga Raga,Rob Zombie,18.0
26,7939,Rock and Roll (in a Black Hole),Rob Zombie,18.0
27,9730,"Behold, The Pretty Filthy Creatures!",Rob Zombie,16.0
28,9731,White Trash Freaks,Rob Zombie,20.0
29,9733,Lucifer Rising,Rob Zombie,15.0
...,...,...,...,...
70,3558,Mary of the Wild Moor,Johnny Cash,10.0
71,39068,Deadlock,Can,NaN
72,8949,Bathwater,No Doubt,40.0
73,297,Dusk (Dark Is Descending),Anathema,156.0
74,298,"The Lost Song, Part 3",Anathema,117.0
75,299,Anathema,Anathema,154.0
76,300,You're Not Alone,Anathema,126.0
77,301,Firelight,Anathema,126.0
78,302,Distant Satellites,Anathema,132.0
79,303,Take Shelter,Anathema,100.0
80,3128,Advent,Opeth,31.0
81,3311,The Night and the Silent Water,Opeth,29.0
82,7218,Nectar,Opeth,18.0
83,7219,Black Rose Immortal,Opeth,25.0
84,8115,To Bid You Farewell,Opeth,34.0
85,289,In Mist She Was Standing,Opeth,25.0
86,290,Under the Weeping Moon,Opeth,28.0
87,291,The Twilight Is My Robe,Opeth,16.0
88,292,The Apostle in Triumph,Opeth,16.0
89,3330,Windowpane,Opeth,112.0
90,2692,In My Time of Need,Opeth,105.0
91,3325,Death Whispered a Lullaby,Opeth,61.0
92,3323,Closure,Opeth,80.0
93,2967,To Rid the Disease,Opeth,55.0
94,3332,Ending Credits,Opeth,60.0
95,3327,Weakness,Opeth,53.0
96,3330,Windowpane,Opeth,112.0
97,2692,In My Time of Need,Opeth,105.0
98,3325,Death Whispered a Lullaby,Opeth,61.0
99,3323,Closure,Opeth,80.0

In [174]:
item_df.drop_duplicates(subset='item_id')

,item_id,track_name,artist_name,interaction
0,72,Needles and Pins,Deftones,42.0
1,73,Minerva,Deftones,99.0
2,74,Good Morning Beautiful,Deftones,42.0
3,75,Deathblow,Deftones,31.0
4,76,When Girls Telephone Boys,Deftones,37.0
5,77,Battle-Axe,Deftones,41.0
6,9725,Lucky You,Deftones,51.0
7,9726,Bloody Cape,Deftones,45.0
8,9727,Anniversary of an Uninteresting Event,Deftones,29.0
9,9762,Moana,Deftones,26.0
10,105,Swerve City,Deftones,131.0
11,24967,Godeatgod,Marilyn Manson,16.0
12,8133,The Fight Song,Marilyn Manson,88.0
13,14852,Disposable Teens,Marilyn Manson,68.0
14,8178,President Dead,Marilyn Manson,13.0
15,24082,Cruci-fiction in Space,Marilyn Manson,20.0
16,7933,A Place in the Dirt,Marilyn Manson,18.0
17,8201,Lamb of God,Marilyn Manson,25.0
18,24345,Born Again,Marilyn Manson,18.0
19,7946,Burning Flag,Marilyn Manson,17.0
20,32430,The Fall of Adam,Marilyn Manson,15.0
21,8167,Mechanical Animals (live),Marilyn Manson,4.0
22,1,Teenage Nosferatu Pussy,Rob Zombie,25.0
23,8250,Revelation Revolution,Rob Zombie,20.0
24,9728,Theme for the Rat Vendor,Rob Zombie,16.0
25,9729,Ging Gang Gong De Do Gong De Laga Raga,Rob Zombie,18.0
26,7939,Rock and Roll (in a Black Hole),Rob Zombie,18.0
27,9730,"Behold, The Pretty Filthy Creatures!",Rob Zombie,16.0
28,9731,White Trash Freaks,Rob Zombie,20.0
29,9733,Lucifer Rising,Rob Zombie,15.0
...,...,...,...,...
611473,27634,Pieces Of A Dream,Incognito,NaN
611547,28025,Still She Cries,Journey,NaN
611721,42581,Ballet Disco,Psychic TV,NaN
611727,33309,Come Ye,Nina Simone,NaN
611773,43326,Misty Roses,Tim Hardin,NaN
611886,43929,Demon Eyes,The Answer,NaN
612063,26393,WaldorfWorldwide,Good Charlotte,NaN
612126,46655,Southern Sun,Paul Oakenfold,NaN
612779,39759,Singing For The Lonely,Robbie Williams,NaN
612801,25082,Looks Like Love,NEEDTOBREATHE,NaN
612805,46685,Second Chances,NEEDTOBREATHE,NaN
613374,9325,Grapefruit - Juicy Fruit,Jimmy Buffett,NaN
613557,36319,Love Scene,Jerry Garcia,NaN
614275,44854,Not For The Innocent,Kiss,NaN
614523,30590,Sleeping Dogs,Psychotic Waltz,NaN
614640,20656,Does The Lion City Still Roar?,Less Than Jake,NaN
614710,30052,Sonnets/Unrealities XI,Björk,1.0
614744,32321,Se A Vida E (That's The Way Life Is),Pet Shop Boys,NaN
614920,48073,Tonight I'm Alright,Narada Michael Walden,NaN
615100,36764,Larger Than Life,Kiss,NaN
615221,45646,Abro la Ventana,Lhasa de Sela,NaN
615298,36115,Andromeda,Hopesfall,NaN
615328,35977,Perverse ... Almost Religious,Moonspell,NaN
615504,46830,Paint It Black,The Feelies,NaN
615510,21942,Mr. Blues,Moby Grape,NaN
615511,45760,Fall on You,Moby Grape,NaN
615512,21943,Come In The Morning,Moby Grape,NaN
615706,13373,Between Worlds,mind.in.a.box,NaN
615739,34688,And you my love,Chris Rea,NaN
615963,23374,Up In You,Vision Of Disorder,NaN

In [175]:
item_df.to_csv('top_250_artist_item.csv')

### 特定のアーティストのアイテムを抽出
 - [人気アーティスト](https://docs.google.com/spreadsheets/d/1R11hDZONuB0rBP-FNAUt_TiArvYpUec9uSZLgCLqAhQ/edit#gid=808250101)

In [194]:
target_artist = 'Lady Gaga'

In [195]:
_target_df = item_df[item_df['artist_name']==target_artist]

In [196]:
_target_df = _target_df.drop_duplicates(subset='item_id')

In [197]:
_target_df

        item_id                          track_name artist_name  interaction
7968       9133                   Dance in the Dark   Lady Gaga         60.0
9247       6251                   Government Hooker   Lady Gaga         63.0
9248       6290                               Judas   Lady Gaga        152.0
9249       8926                           Americano   Lady Gaga         71.0
9250       6237                         Bloody Mary   Lady Gaga         72.0
9251       6232                            Bad Kids   Lady Gaga         58.0
9252       6288      Highway Unicorn (Road to Love)   Lady Gaga         59.0
12924      8900                           Paparazzi   Lady Gaga        127.0
16304      9135                               Teeth   Lady Gaga         55.0
16305      6265                          Just Dance   Lady Gaga        113.0
16307      8901              Beautiful, Dirty, Rich   Lady Gaga         46.0
16308      6250                            The Fame   Lady Gaga         33.0
16309      8246                         Money Honey   Lady Gaga         32.0
16310      8902                          Starstruck   Lady Gaga         34.0
16311      8903                      Boys Boys Boys   Lady Gaga         51.0
16312      8904                       Paper Gangsta   Lady Gaga         41.0
16313      5807                     I Like It Rough   Lady Gaga         31.0
16314      8906                           Summerboy   Lady Gaga         44.0
16315      6236                        Disco Heaven   Lady Gaga         20.0
39872      9134                So Happy I Could Die   Lady Gaga         64.0
81043     24018       Judas (DJ White Shadow Remix)   Lady Gaga         10.0
116322    24029  Just Dance (Richard Vission Remix)   Lady Gaga          7.0
138802    46173                           Telephone   Lady Gaga          5.0
272663     6289                   Retro Dance Freak   Lady Gaga          3.0
282568    36752             Judas (Goldfrapp Remix)   Lady Gaga          3.0
331343    14011                 Judas (Hurts Remix)   Lady Gaga          1.0
449420     9136       Bad Romance (Starsmith Remix)   Lady Gaga          3.0

In [198]:
path = './artist_item_data/' 

if not os.path.exists(path):
    os.makedirs(path)
    
_target_df.to_csv(path + '{}.csv'.format(target_artist))